language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.0.0
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
notifications:
  email: false
gemfile: Gemfile