language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script: bundle exec rake test
branches:
  only:
    - master
env:
  - PUPPET_VERSION="3.6.0"
  - PUPPET_VERSION="3.7.0"
  - PUPPET_VERSION="4.0.0"
  - PUPPET_VERSION="4.1.0"
notifications:
  email: false
gemfile: Gemfile